# Generated by Django 3.1.5 on 2021-04-25 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('songid', models.AutoField(primary_key=True, serialize=False)),
                ('songname', models.CharField(max_length=200)),
                ('media', models.CharField(max_length=500)),
                ('img', models.CharField(max_length=500)),
            ],
        ),
    ]
